export const data = [
  {
    title: "Basic Cotton T-Shirt",
    price: 19.99,
    category: "673dbfabe73f709aace7732b",
    discountPercentage: 10,
    ratings: [5, 4, 3],
    stock: 0,
    description: "Comfortable and breathable cotton t-shirt for daily wear.",
    images: [
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
    ],
    attributes: {
      sizes: [
        { size: "S", stock: 0 },
        { size: "M", stock: 0 },
        { size: "L", stock: 0 },
        { size: "XL", stock: 0 },
      ],
      colours: ["black", "white", "blue"],
    },
  },
  {
    title: "Wireless Mouse",
    price: 29.99,
    category: "673dbfa3e73f709aace77328",
    discountPercentage: 15,
    ratings: [4, 5],
    stock: 100,
    description: "Ergonomic wireless mouse with a 2-year battery life.",
    images: [
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
    ],
    attributes: {
      sizes: [],
      colours: ["black", "white"],
    },
  },
  {
    title: "Running Shoes",
    price: 49.99,
    category: "673dbfafe73f709aace7732e",
    discountPercentage: 5,
    ratings: [5, 5, 4, 3],
    stock: 0,
    description: "Lightweight and comfortable running shoes for all terrains.",
    images: [
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
    ],
    attributes: {
      sizes: [
        { size: "39", stock: 8 },
        { size: "40", stock: 12 },
        { size: "41", stock: 10 },
        { size: "42", stock: 5 },
      ],
      colours: ["black", "gray"],
    },
  },
  {
    title: "Leather Wallet",
    price: 24.99,
    category: "673dbfbce73f709aace77331",
    discountPercentage: 0,
    ratings: [4, 4, 5],
    stock: 50,
    description: "Durable leather wallet with multiple compartments.",
    images: [
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
    ],
    attributes: {
      sizes: [],
      colours: ["red", "black"],
    },
  },
  {
    title: "Good Cotton T-Shirt",
    price: 29.99,
    category: "673dbfabe73f709aace7732b",
    discountPercentage: 0,
    ratings: [5, 4, 3, 5],
    stock: 0,
    description: "Comfortable and breathable cotton t-shirt for daily wear.",
    images: [
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
      "https://images.teemill.com/2qczyrcpoxoa68qdd0nkyaedcaunbavwo0klypsssippxue2.png.png?w=1080&h=auto",
    ],
    attributes: {
      sizes: [
        { size: "S", stock: 10 },
        { size: "M", stock: 20 },
        { size: "L", stock: 15 },
        { size: "XL", stock: 0 },
      ],
      colours: ["black", "white", "blue"],
    },
  },
  {
    title: "Good Wireless Mouse",
    price: 39.99,
    category: "673dbfa3e73f709aace77328",
    discountPercentage: 15,
    ratings: [4, 5, 2, 1],
    stock: 0,
    description: "Ergonomic wireless mouse with a 2-year battery life.",
    images: [
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
      "https://png.pngtree.com/png-vector/20240625/ourlarge/pngtree-black-wireless-computer-mouse-png-image_12851844.png",
    ],
    attributes: {
      sizes: [],
      colours: ["black", "white"],
    },
  },
  {
    title: "Good Running Shoes",
    price: 59.99,
    category: "673dbfafe73f709aace7732e",
    discountPercentage: 5,
    ratings: [5, 5, 4, 3, 1, 2],
    stock: 0,
    description: "Lightweight and comfortable running shoes for all terrains.",
    images: [
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
      "https://static.vecteezy.com/system/resources/previews/036/625/143/non_2x/ai-generated-sports-shoes-for-the-future-running-shoes-for-the-future-isolated-on-transparent-background-free-png.png",
    ],
    attributes: {
      sizes: [
        { size: "39", stock: 8 },
        { size: "40", stock: 12 },
        { size: "41", stock: 10 },
        { size: "42", stock: 5 },
      ],
      colours: ["black", "gray"],
    },
  },
  {
    title: "BestLeather Wallet",
    price: 44.99,
    category: "673dbfbce73f709aace77331",
    discountPercentage: 0,
    ratings: [4, 4, 5],
    stock: 50,
    description: "Durable leather wallet with multiple compartments.",
    images: [
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
      "https://wallpapers.com/images/hd/leather-wallets-stacked-hq6xo9yj4rcap0wg-2.jpg",
    ],
    attributes: {
      sizes: [],
      colours: ["red", "black"],
    },
  },
];
